#!/bin/bash
LOGFILE_PATH="bld.log"
rm a.out
if [ "$SATA_PATH" == '' ]
then
    export SATA_PATH=".."
fi
if [ "$UNISIMS_PATH" == '' ]
then
    export UNISIMS_PATH="../../../../eddr3-src/eddr3/unisims"
fi
iverilog $SATA_PATH/tb/tb_top.v -f opts  -stb $1 2>&1| tee $LOGFILE_PATH
 
#-y$SATA_PATH/x393/util_modules -I$SATA_PATH/x393/ -I$SATA_PATH/x393/axi/ $SATA_PATH/tb/tb_axiregs.v -I$SATA_PATH/ -I$SATA_PATH/tb/

